version: "3"

services:
  mariadb-galera-0:
    image: bitnami/mariadb-galera:latest
    restart: always
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb-galera/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./galera/node0/data:/bitnami/mariadb
    environment:
      TZ: ${TZ}
      NODE_NAME: "NODE0"
      MARIADB_GALERA_NODE_ADDRESS: ${GALERA_CLUSTER_NODE0}
      MARIADB_GALERA_CLUSTER_BOOTSTRAP: "yes"
      MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP: "yes"
      MARIADB_GALERA_CLUSTER_NAME: ${MARIADB_GALERA_CLUSTER_NAME}
      MARIADB_GALERA_MARIABACKUP_USER: ${MARIADB_GALERA_MARIABACKUP_USER}
      MARIADB_GALERA_MARIABACKUP_PASSWORD: ${MARIADB_GALERA_MARIABACKUP_PASSWORD}
      MARIADB_REPLICATION_USER: ${MARIADB_REPLICATION_USER}
      MARIADB_REPLICATION_PASSWORD: ${MARIADB_REPLICATION_PASSWORD}

      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    network_mode: host
    # ports:
    #   - "3306:3306"
    #   - "4444:4444"
    #   - "4567:4567"
    #   - "4568:4568"
